version: '3.8'
services:
  auth:
    container_name: auth
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=mysql://root:root@db:3306/auth
    ports:
      - 3001:3001
    depends_on:
      - db
  db:
    image: mysql:8.0
    restart: always
    container_name: mysqldb-skripsi
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: auth-skripsi
      MYSQL_PASSWORD: auth123
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    container_name: phpmyadmin-skripsi
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - 8080:80
    depends_on:
      - db
  jaeger:
    image: jaegertracing/all-in-one:latest
    hostname: localhost
    container_name: jaeger-skripsi
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - 16686:16686
      - 14268:14268
  prometheus:
   image: prom/prometheus
   container_name: prometheus
   user: root
   volumes:
     - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
     - ./prometheus/data:/prometheus
   ports:
     - 9090:9090
   command: 
     - '--config.file=/etc/prometheus/prometheus.yml'
     - '--storage.tsdb.path=/prometheus'
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "1000:1000"
    volumes:
      - ./grafana:/var/lib/grafana
    ports:
      - 3010:3000
    depends_on:
      - prometheus
      - jaeger
  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    ports:
      - 9100:9100
  loki:
    image: grafana/loki:latest
    container_name: loki
    user: root
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yml
    volumes:
      - ./loki:/etc/loki
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    user: root
    ports:
      - 9080:9080
    volumes:
      - ./promtail:/etc/promtail
    command: -config.file=/etc/promtail/config.yml
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    ports:
      - 4317:4317
      - 4318:4318
    depends_on:
      - jaeger
    volumes:
      - ./otel-collector/config.yaml:/otel/config.yaml
    command: ["--config=/otel/config.yaml"]
