receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  jaeger:
    endpoint: "http://localhost:14268"
    insecure: true

processors:
  batch:
    timeout: 10s

extensions:
  health_check:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger]
