receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
    loglevel: debug
  jaeger:
    endpoint: jaeger-skripsi:14250
    tls:
      insecure: true

processors:
  batch:
    timeout: 10s
  attributes/example:
    actions:
      - key: rizkal
        value: ganteng
        action: upsert

extensions:
  health_check:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, attributes/example]
      exporters: [logging, jaeger]
