apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: haritsrizkal/obs-micro-auth:1.0.4
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
            - name: DATABASE_URL
              value: "mysql://root:root@mysql.app.svc.cluster.local:3306/auth"
            - name: OTEL_COLLECTOR_ENDPOINT
              value: "http://otel-collector-collector.observability.svc.cluster.local:4318/v1/traces"
            - name: IS_TRACING_ENABLED
              value: "true"
            - name: IS_ERROR_ENABLED
              value: "false"
            - name: IS_BOTTLENECK_ENABLED
              value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app: auth
spec:
  type: NodePort
  selector:
    app: auth
  ports:
    - port: 3001
      targetPort: 3001
      nodePort: 32767
