apiVersion: apps/v1
kind: Deployment
metadata: 
  name: auth-deployment
  labels: 
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: haritsrizkal/obs-micro-auth:1.0.2
          ports: 
            - containerPort: 3001
          env: 
            - name: PORT
              value: "3001"
            - name: DATABASE_URL
              value: "mysql://root:root@mysql.default.svc.cluster.local:3306/auth"
            - name: OTEL_COLLECTOR_ENDPOINT
              value: "http://simplest-collector.default.svc.cluster.local:4318/v1/traces"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app: auth
spec:
  type: NodePort
  selector:
    app: auth
  ports:
    - port: 3001
      targetPort: 3001
      nodePort: 32767
