apiVersion: apps/v1
kind: Deployment
metadata: 
  name: catalog-deployment
  labels: 
    app: catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
        - name: catalog
          image: haritsrizkal/obs-micro-catalog:1.0.0
          ports: 
            - containerPort: 3004
          env:
            - name: PORT
              value: "3004"
            - name: DATABASE_URL
              value: "mysql://root:root@mysql.default.svc.cluster.local:3306/catalog"
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  labels:
    app: catalog
spec:
  type: NodePort
  selector:
    app: catalog
  ports:
    - port: 3004
      targetPort: 3004
      nodePort: 32766