apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.7.0
  nodeSets:
    - name: default
      count: 1
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
            storageClassName: hostpath
      config:
        node.store.allow_mmap: false
  # http:
  #   tls:
  #     selfSignedCertificate:
  #       disabled: true
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
spec:
  version: 7.7.0
  # http:
  #   tls:
  #     selfSignedCertificate:
  #       disabled: true
  count: 1
  elasticsearchRef:
    name: quickstart
