apiVersion: apps/v1
kind: Deployment
metadata:
  name: merchant-deployment
  labels:
    app: merchant
spec:
  replicas: 2
  selector:
    matchLabels:
      app: merchant
  template:
    metadata:
      labels:
        app: merchant
    spec:
      containers:
        - name: merchant
          image: haritsrizkal/obs-micro-merchant:1.0.6
          ports:
            - containerPort: 3003
          env:
            - name: PORT
              value: "3003"
            - name: DATABASE_URL
              value: "mysql://root:root@mysql.app.svc.cluster.local:3306/merchant"
            - name: OTEL_COLLECTOR_ENDPOINT
              value: "http://otel-collector-collector.observability.svc.cluster.local:4318/v1/traces"
            - name: IS_TRACING_ENABLED
              value: "true"
            - name: IS_ERROR_ENABLED
              value: "false"
            - name: IS_BOTTLENECK_ENABLED
              value: "false"
            - name: AUTH_SERVICE_URL
              value: "http://auth-service.app.svc.cluster.local:3001/api/auth/"
            - name: MERCHANT_SERVICE_URL
              value: "http://merchant-service.app.svc.cluster.local:3003/api/merchant/"
            - name: CATALOG_SERVICE_URL
              value: "http://catalog-service.app.svc.cluster.local:3004/api/catalog/"
            - name: ORDER_SERVICE_URL
              value: "http://order-service.app.svc.cluster.local:3002/api/order/"
            - name: PAYMENT_SERVICE_URL
              value: "http://payment-service.app.svc.cluster.local:3005/api/payment/"
---
apiVersion: v1
kind: Service
metadata:
  name: merchant-service
  labels:
    app: merchant
spec:
  type: NodePort
  selector:
    app: merchant
  ports:
    - port: 3003
      targetPort: 3003
      nodePort: 32765
