apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
  labels:
    app: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: haritsrizkal/obs-micro-payment:1.0.4
          ports:
            - containerPort: 1323
          env:
            - name: PORT
              value: "1323"
            - name: DATABASE_URL
              value: "root:root@tcp(mysql.app.svc.cluster.local:3306)/payment?charset=utf8mb4&parseTime=True&loc=Local"
            - name: OTEL_COLLECTOR_ENDPOINT
              value: "otel-collector-collector.observability.svc.cluster.local:4318"
            - name: IS_TRACING_ENABLED
              value: "false"
            - name: IS_ERROR_ENABLED
              value: "false"
            - name: IS_BOTTLENECK_ENABLED
              value: "false"
            - name: OTEL_SAMPLING_RATIO
              value: "1"
            - name: OTEL_MAX_QUEUE_SIZE
              value: "10000"
            - name: OTEL_MAX_EXPORT_BATCH_SIZE
              value: "5000"
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  labels:
    app: payment
spec:
  type: NodePort
  selector:
    app: payment
  ports:
    - port: 1323
      targetPort: 1323
